name: Project CI Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  # Job 1: Mengecek Backend (Go)
  backend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Check Service Employee
        run: |
          cd service-employee
          go mod download
          go build -o main .

      - name: Check Service Customer
        run: |
          cd service-customer
          go mod download
          go build -o main .

  # Job 2: Mengecek Frontend (React)
  frontend-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build React
        run: |
          cd frontend-idstar
          npm install
          npm run build